Flexport/EngineApiBoundary:
  Description: 'Use Rails Engine APIs instead of arbitrary code access.'
  Enabled: false
  VersionAdded: '0.3.0'
  EnginesPath: 'engines/'
  UnprotectedEngines: []
  StronglyProtectedEngines: []
  EngineSpecificOverrides: []
  FactoryBotOutboundAccessAllowedEngines: []

Flexport/GlobalModelAccessFromEngine:
  Description: 'Do not directly access global models from within Rails Engines.'
  Enabled: false
  VersionAdded: '0.2.0'
  AutoCorrect: false
  EnginesPath: engines/
  GlobalModelsPath: app/models/
  DisabledEngines: []
  AllowedGlobalModels: []
  FactoryBotGlobalAccessAllowedEngines: []
  Include:
    - '**/*.rb'

Flexport/NewGlobalModel:
  Description: 'Disallows addition of new global models to `app/models`. Prefer Rails Engines or namespaces.'
  Enabled: true
  VersionAdded: '0.1.0'
  GlobalModelsPath: 'app/models/'
  AllowNamespacedGlobalModels: true
