Flexport/GlobalModelAccessFromEngine:
  Description: 'Do not directly access global models from within Rails Engines.'
  Enabled: false
  VersionAdded: '0.2.0'
  AutoCorrect: false
  EnginesPath: engines/
  GlobalModelsPath: app/models/
  DisabledEngines: []
  AllowedGlobalModels: []
  Include:
    - '**/*.rb'

Flexport/NewGlobalModel:
  Description: 'Disallows addition of new global models to `app/models`. Prefer Rails Engines or namespaces.'
  Enabled: true
  VersionAdded: '0.1.0'
  GlobalModelsPath: 'app/models/'
  AllowNamespacedGlobalModels: true
